version: '3'
services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=snap
      - POSTGRES_USER=snap
    hostname: postgres-assignments
    container_name: postgres-assignments
